### PR TITLE
Fix bug

### PR DESCRIPTION
**Pull request by Graf009**
Fix bug  #10

### CODE REVIEW

**Comment by Graf009** [comment]
Please update the package on npm

**Comment by ruprict** [comment]
Was this ever updated on npm? rc3 doesn't have the fix and that's the latest version on npm....

**Comment by quirinpa** [comment]
I want it baaad

**Comment by ruprict** [comment]
So, fwiw, I made a branch on my fork that you can use in your package.json to move forward until we get a new npm module. 

https://github.com/ruprict/redux-localstorage/tree/install-via-git

So, in `package.json`:
```
...
"redux-localstorage": "ruprict/redux-localstorage#install-via-git"
...
```

It also has a hack to fix [this issue](https://github.com/elgerlambert/redux-localstorage/issues/13)

**Comment by elgerlambert** [comment]
Thanks @ruprict for jumping in and helping out! I finally managed to publish this fix to npm as rc4.

**Pull request merged**
